import type { Metadata } from "next";
import "./globals.css";
import { lato } from "./ui/fonts";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { ClerkProvider } from "@clerk/nextjs";
import { NextUIProvider } from "@nextui-org/system";
import NavBar from "./nav-bar/nav-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${lato.className}`}>
          <NextUIProvider className="bg-gray-200 min-h-screen flex flex-col overflow-x-hidden`">
            <NavBar></NavBar>
            <EdgeStoreProvider>{children}</EdgeStoreProvider>
          </NextUIProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
